### ISSUE TITLE
Does not work with React Native Expo

### ISSUE THREAD

**Issue by charlestbell** [kettanaito/msw#1005]
## Describe the bug
I cannot get MSW to work with an Expo-managed native app. I made a clean install to demonstrate what I mean:
https://github.com/charlestbell/Mock-Service-Worker-Debug

## Environment

- msw: 0.35.0,
- nodejs: v14.17.1
- npm: 6.14.13
- expo: 43.0.2,
- react-native: 0.64.3,

## To Reproduce
1. Download the repo and unpack it.
2. `cd` into `Mock-Service-Worker-Debug` folder
3. Install dependencies. I use the `yarn` command
4. Run tests. I use `yarn test`
5. Test fails
6. You can see in debug printout in the console that nothing was returned from MSW, and the original 'noValue' remains.

## Expected behavior
MSW responds with the values written in `App.test.js`

**Comment by kettanaito** [comment]
Hey, @charlestbell. 

If you wrap your `fetchEndpoint` logic in a `try/catch` block you will see the actual culprit:

```sh
console.log
  ReferenceError: fetch is not defined
      at fetchEndpoint$ (/contrib/1005-msw-react-native-expo/App.js:8:25)
      at tryCatch (/contrib/1005-msw-react-native-expo/node_modules/regenerator-runtime/runtime.js:63:40)
      at Generator.invoke [as _invoke] (/contrib/1005-msw-react-native-expo/node_modules/regenerator-runtime/runtime.js:294:22)
      at Generator.next (/contrib/1005-msw-react-native-expo/node_modules/regenerator-runtime/runtime.js:119:21)
      at tryCatch (/contrib/1005-msw-react-native-expo/node_modules/regenerator-runtime/runtime.js:63:40)
      at invoke (/contrib/1005-msw-react-native-expo/node_modules/regenerator-runtime/runtime.js:155:20)
      at /contrib/1005-msw-react-native-expo/node_modules/regenerator-runtime/runtime.js:190:11
      at tryCallTwo (/contrib/1005-msw-react-native-expo/node_modules/react-native/node_modules/promise/lib/core.js:45:5)
      at doResolve (/contrib/1005-msw-react-native-expo/node_modules/react-native/node_modules/promise/lib/core.js:200:13)
      at new Promise (/contrib/1005-msw-react-native-expo/node_modules/react-native/node_modules/promise/lib/core.js:66:3)
```

> I don't know why you don't see this runtime exception by default in your tests. You should consider investigating this and ensure such exceptions are properly reported. This is likely a test runner configuration issue.

The thing is, `fetch` is not defined in React Native and you need to use a suitable polyfill. Once the polyfill is in place, the request will happen and MSW will catch that request according to the handlers you've defined. 

I've used [`cross-fetch`](https://lquixada.github.io/cross-fetch/) polyfill, which supports React Native, and can confirm your test is passing without issues (you received the mocked response). Here's how I did it:

```jsx
// App.test.js
// Add the "fetch" polyfill at the top of your test file.
import 'cross-fetch/polyfill'
```

Ideally, you should import the polyfill in your `jest.setup.js` file and provide it to `setupFilesAfterEnv` option in `jest.config.js` so that all test suites have the polyfill enabled.
