### ISSUE TITLE
Is MSW compatible with ES5?

### ISSUE THREAD

**Issue by Char1zardd** [kettanaito/msw#1111]
I am attempting to use msw in a codebase that is entirely written in ES5. I am attempting the following below. Note I also tried using babel to transpile

## Environment
- `msw: 0.38.1`
- `nodejs: 17.3.0`
- `npm: 8.3.0`
- `os: Ubuntu 20.04`

## Request handlers

```js
const { rest } = require('msw')
const { setupServer } = require('msw/node')

let handlers = []
handlers.push(
	rest.get('https://code.jquery.com/jquery-3.6.0.js', (req, res, ctx) => {
		return res(
			ctx.status(200),
			ctx.json({
				type: "jquery",
				status: "ok"
			})
			)
	})
)

const server = setupServer(handlers)

server.listen()
```

## Actual request
The request is simply made with https library

```js
const https = require('https')

const url = 'https://code.jquery.com/jquery-3.6.0.js'
const filename = url.split('/').pop()
const dest = path.join('./', filename)
https.get(url, response => {
    const writeStream = fs.createWriteStream(dest)
    response.pipe(writeStream)
    writeStream.on('error', () => console.error('Error writing to ' + path.resolve(dest)))
    writeStream.on('finish', () => writeStream.close())
})
```

## Current behavior

Currently the error stack mentions that there is the following error: `context: TypeError: Cannot read properties of undefined (reading 'test')`

## Expected behavior

I expect my test to pass since I have mocked the downloading of jquery, 

## Screenshots

Here is a more detailed traceback of the error:
```js
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  code: 'ERR_UNHANDLED_ERROR',
  context: TypeError: Cannot read properties of undefined (reading 'test')
      at /home/desktop/Apps/Superalgos_DEV/Superalgos/node_modules/msw/node/lib/index.js:2969:24
      at Array.filter (<anonymous>)
      at /home/desktop/Apps/Superalgos_DEV/Superalgos/node_modules/msw/node/lib/index.js:2968:39
      at Generator.next (<anonymous>)
      at /home/desktop/Apps/Superalgos_DEV/Superalgos/node_modules/msw/node/lib/index.js:54:71
      at new Promise (<anonymous>)
      at __awaiter (/home/desktop/Apps/Superalgos_DEV/Superalgos/node_modules/msw/node/lib/index.js:50:12)
      at getResponse (/home/desktop/Apps/Superalgos_DEV/Superalgos/node_modules/msw/node/lib/index.js:2967:63)
      at /home/desktop/Apps/Superalgos_DEV/Superalgos/node_modules/msw/node/lib/index.js:8044:36
      at Generator.next (<anonymous>)
}
```

**Comment by kettanaito** [comment]
Hi, @Char1zardd. 

MSW is fully compatible with ES5. 

The issue you're experiencing is caused by the way you provide the `handlers` to `setupServer`:

```diff
-setupServer(handlers)
+setupServer(...handlers)
```

The `handlers` array must be destructured onto the `setupServer` call. Once you do this, the error will be gone. 

> This is interesting, as you should really see an error from MSW suggesting you do that.
