### ISSUE TITLE
How to fix this error? (semicolon missing)

### ISSUE THREAD

**Issue by cjy0019** [kettanaito/msw#1274]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Reproduction repository

https://github.com/cjy0019/cherry-front

### Reproduction steps

`src/mocks/browser.js`
```js
import { setupWorker } from 'msw';
import { handlers } from './handlers';

export const worker = setupWorker(...handlers);
```

`src/mocks/handler.js`

```js
import { rest } from 'msw';

const todos = ['먹기', '자기', '놀기'];

export const handlers = [
  rest.get('/todos', (req, res, ctx) => {
    return res(ctx.status(200), ctx.json(todos));
  }),
  // 할일 추가
  rest.post('/todos', (req, res, ctx) => {
    todos.push(req.body);
    return res(ctx.status(201));
  }),
];
```

`/index.js`
```js
import React from 'react';
import ReactDOM from 'react-dom';
import App from './App';
import { worker } from './mocks/browser';

if (process.env.NODE_ENV === 'development') {
  worker.start();
}

ReactDOM.render(
  <>
    <App />
  </>,
  document.getElementById('root'),
);
```

### Current behavior

<img width="1075" alt="스크린샷 2022-06-06 오후 2 01 43" src="https://user-images.githubusercontent.com/33951916/172097851-936e11cb-0db3-49c9-a9b0-90cf8dac6f1f.png">

### Expected behavior

this code is not working.. how can i solve it.. plz

**Comment by kettanaito** [comment]
Hey, @cjy0019. 

At the first glance, it looks like Babel cannot process `node_modules/statuses/codes.json`. Can you make sure your project setup can handle JSON imports just to be safe? I also wonder what's going to happen if you install `statuses` directly and import it in your app.

**Comment by cjy0019** [comment]
@kettanaito 
thank you for comment.. this is my `.babelrc`, `webpack.config.js`
I don't know what the problem is.

`.babelrc`
```json
{
  "presets": [
    [
      "@babel/preset-env",
      { "targets": { "browsers": ["last 2 versions", ">= 5% in KR"] } }
    ],
    "@babel/react"
  ],
  "plugins": [
    "babel-plugin-styled-components",
    [
      "@babel/plugin-transform-runtime",
      {
        "absoluteRuntime": false,
        "corejs": 3,
        "helpers": true,
        "regenerator": true,
        "version": "7.0.0-beta.0"
      }
    ]
  ]
}
```

`webpack.config.js`
```js
const path = require('path');
const HtmlWebPackPlugin = require('html-webpack-plugin');
const CaseSensitivePathsWebpackPlugin = require('case-sensitive-paths-webpack-plugin');

module.exports = {
  entry: './src/index.jsx',
  devServer: {
    hot: true,
    open: true,
    port: 3000,
    historyApiFallback: { index: '/', disableDotRule: true },
  },
  mode: 'development',
  module: {
    rules: [
      {
        test: /\.html$/,
        use: [
          {
            loader: 'html-loader',
            options: { minimize: true },
          },
        ],
      },
      {
        test: /\.jsx?/,
        exclude: '/node_modules',
        use: ['babel-loader'],
      },
      {
        test: /\.(woff|ttf)$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              fallback: 'file-loader',
              name: 'fonts/[name].[ext]',
            },
          },
        ],
      },
      {
        // write image files under 10k to inline or copy image files over 10k
        test: /\.(jpg|jpeg|gif|png|svg|ico)?$/,
        use: [
          {
            loader: 'url-loader',
            options: {
              limit: 10000,
              fallback: 'file-loader',
              name: 'img/[name].[ext]',
            },
          },
        ],
      },
    ],
  },
  plugins: [
    new HtmlWebPackPlugin({
      template: './public/index.html',
      filename: 'index.html',
    }),
    new CaseSensitivePathsWebpackPlugin({ debug: true }),
  ],
  resolve: {
    extensions: ['.jsx', '.js'],
  },
  output: {
    filename: 'main.js',
    publicPath: '/',
    path: path.join(__dirname, '/dist'),
  },
};
```

**Comment by kettanaito** [comment]
Hey, @cjy0019. I've cloned your reproduction repository but it doesn't include the files you're mentioning. It doesn't use `msw` either. Perhaps, you've linked the wrong repo?

Please, double-check and update it if that's the case. I cannot look into this issue with a repo.

**Comment by cjy0019** [comment]
Oh sorry, @kettanaito.
It hasn't merged into the main branch yet! Now that I've merged it, would you like to try clone it again?

**Comment by kettanaito** [comment]
No worries, @cjy0019. I will look into it.

**Comment by cjy0019** [comment]
Hey, @kettanaito did you solved it? haha

**Comment by kettanaito** [comment]
As I've suspected, your project configuration doesn't know how to handle `*.json` imports. You can verify this yourself by importing `statuses` directly:

```js
// src/index.jsx
// ...

import { codes } from 'statuses';
console.log({ codes });
```

The compilation result you get from webpack:

```
ERROR in ./node_modules/statuses/codes.json
Module build failed (from ./node_modules/babel-loader/lib/index.js):
SyntaxError: /Users/kettanaito/Projects/contrib/cherry-front/node_modules/statuses/codes.json: Missing semicolon. (2:7)

  1 | {
> 2 |   "100": "Continue",
    |        ^
  3 |   "101": "Switching Protocols",
  4 |   "102": "Processing",
  5 |   "103": "Early Hints",
    at Parser._raise (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:476:17)
    at Parser.raiseWithData (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:469:17)
    at Parser.raise (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:430:17)
    at Parser.semicolon (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:3767:10)
    at Parser.parseExpressionStatement (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:14697:10)
    at Parser.parseStatementContent (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:14261:19)
    at Parser.parseStatement (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:14113:17)
    at Parser.parseBlockOrModuleBlockBody (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:14739:25)
    at Parser.parseBlockBody (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:14730:10)
    at Parser.parseBlock (/Users/kettanaito/Projects/contrib/cherry-front/node_modules/@babel/parser/lib/index.js:14714:10)
 @ ./node_modules/statuses/index.js 13:12-35
 @ ./src/index.jsx 6:0-33 8:9-14
```

The issue is not related to MSW. Please make sure to configure your project to understand JSON imports. Once you do, there will be no issues importing `statuses` which is a transient dependency of MSW.

**Comment by lq513** [comment]
`test: /\.jsx?/ ` should be change to `test: /\.jsx?$/ `

`/\.jsx?/.test('.json') // true`
