### ISSUE TITLE
Storybook build crashes with msw@0.49.3

### ISSUE THREAD

**Issue by cameron-yee** [kettanaito/msw#1525]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

14.21.1

### Reproduction repository

https://github.com/mswjs/examples/tree/master/examples/with-storybook

### Reproduction steps

1. git clone https://github.com/mswjs/examples.git
2. cd examples
3. yarn install
4. cd examples/with-storybook
5. yarn build-storybook

### Current behavior

```
yarn run v1.22.19
warning package.json: No license field
$ build-storybook -s public
info @storybook/react v6.5.15
info
info => Cleaning outputDir: <my-dir>/with-storybook/storybook-static
(node:56110) DeprecationWarning: --static-dir CLI flag is deprecated, see:

https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated---static-dir-cli-flag
(Use `node --trace-deprecation ...` to show where the warning was created)
info => Loading presets
info => Copying static files: ./public => ./
info => Compiling manager..
info => Compiling preview..
info => Using implicit CSS loaders
(node:56110) DeprecationWarning: Default PostCSS plugins are deprecated. When switching to '@storybook/addon-postcss',
you will need to add your own plugins, such as 'postcss-flexbugs-fixes' and 'autoprefixer'.

See https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#deprecated-default-postcss-plugins for details.
info => Using default Webpack4 setup
92% chunk asset optimization TerserPlugininfo => Manager built (9.73 s)
ERR! => Failed to build the preview
ERR! ./node_modules/strict-event-emitter/lib/Emitter.js 14:10
ERR! Module parse failed: Unexpected token (14:10)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
ERR! |  */
ERR! | class Emitter {
ERR! >     events;
ERR! |     maxListeners;
ERR! |     hasWarnedAboutPotentialMemortyLeak;
ERR!  @ ./node_modules/strict-event-emitter/lib/index.js 17:13-33
ERR!  @ ./node_modules/msw/lib/index.js
ERR!  @ ./stories/GitHubUser.stories.js
ERR!  @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
ERR!  @ ./generated-stories-entry.js
ERR!  @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
ERR! ./node_modules/strict-event-emitter/lib/MemoryLeakError.js 5:11
ERR! Module parse failed: Unexpected token (5:11)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
ERR! | exports.MemoryLeakError = void 0;
ERR! | class MemoryLeakError extends Error {
ERR! >     emitter;
ERR! |     type;
ERR! |     count;
ERR!  @ ./node_modules/strict-event-emitter/lib/index.js 18:13-41
ERR!  @ ./node_modules/msw/lib/index.js
ERR!  @ ./stories/GitHubUser.stories.js
ERR!  @ ./stories sync ^\.(?:(?:^|\/|(?:(?:(?!(?:^|\/)\.).)*?)\/)(?!\.)(?=.)[^/]*?\.stories\.js)$
ERR!  @ ./generated-stories-entry.js
ERR!  @ multi ./node_modules/@storybook/core-client/dist/esm/globals/polyfills.js ./node_modules/@storybook/core-client/dist/esm/globals/globals.js ./storybook-init-framework-entry.js ./node_modules/@storybook/react/dist/esm/client/preview/config-generated-config-entry.js ./node_modules/@storybook/addon-actions/preview.js-generated-config-entry.js ./node_modules/@storybook/addon-links/preview.js-generated-config-entry.js ./.storybook/preview.js-generated-config-entry.js ./generated-stories-entry.js
ERR! Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /Users/practice/with-storybook/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:249:60
ERR!     at finalCallback (/Users//practice/with-storybook/node_modules/webpack/lib/Compiler.js:257:39)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:273:13
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at onCompiled (/Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:271:21)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:681:15
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:678:31
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compilation.js:1423:35
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compilation.js:1414:32
ERR!     at eval (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
ERR!  Error: => Webpack failed, learn more with --debug-webpack
ERR!     at /Users/practice/with-storybook/node_modules/@storybook/builder-webpack4/dist/cjs/index.js:249:60
ERR!     at finalCallback (/Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:257:39)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:273:13
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at onCompiled (/Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:271:21)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:681:15
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compiler.js:678:31
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compilation.js:1423:35
ERR!     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:9:1)
ERR!     at AsyncSeriesHook.lazyCompileHook (/Users/practice/with-storybook/node_modules/tapable/lib/Hook.js:154:20)
ERR!     at /Users/practice/with-storybook/node_modules/webpack/lib/Compilation.js:1414:32
ERR!     at eval (eval at create (/Users/practice/with-storybook/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:18:1)
ERR!     at processTicksAndRejections (internal/process/task_queues.js:95:5)
info => Loading presets
error Command failed with exit code 1.
```

### Expected behavior

Storybook should build as expected. Locking `msw` at version `0.49.2` resolves the issue, so there must be a bug with a commit in `0.49.3`.

**Comment by gosua** [comment]
Since `msw` version `0.4.3`, our project build is also broken. 

First, we experienced the problem because of the private class field modifier. This got fixed with https://github.com/open-draft/strict-event-emitter/pull/12. 

Now, we are experiencing the same problem as mentioned above:
```
...
ERR! Module parse failed: Unexpected token (5:11)
ERR! You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
ERR! | exports.MemoryLeakError = void 0;
ERR! | class MemoryLeakError extends Error {
ERR! >     emitter;
ERR! |     type;
ERR! |     count;
...
```

Adding dedicated webpack loaders just to have the `msw` version bumped seems like an ugly workaround.

**Comment by w1nklr** [comment]
Same for me. I can't update to `msw` version `0.49.3` nor `1.0.0`.
Last version I can use is `0.49.2` :(

**Comment by paazmaya** [comment]
The root cause and a fix for it https://github.com/open-draft/strict-event-emitter/pull/13

**Comment by adamsoderstrom** [comment]
Changing the `"msw": "latest"` to `"msw": "0.49.3"` in [`with-storybooks`'s `package.json`](https://github.com/mswjs/examples/blob/71a76d223296162f3af9bbb9d281a32421d00fc7/examples/with-storybook/package.json#L12) and running the issue's "steps to reproduce" resulted in a complete build for me now.

**Comment by kettanaito** [comment]
Hi. Thanks for reporting this. Can you please try re-installing the library? This issues has been fixed in `strict-event-emitter@0.4.6` and MSW currently depends on the `^0.4.3` range for that dependency. Re-installing your dependencies will pull the latest version of `strict-event-emitter`, fixing the issue for you. Thanks.

**Comment by AndrewBogdanovTSS** [comment]
@kettanaito works for me

**Comment by w1nklr** [comment]
@kettanaito Yes, `strict-event-emitter` was the issue. Works fine now.
Thanks

**Comment by kettanaito** [comment]
Closing this. The fix is mentioned [here](https://github.com/mswjs/msw/issues/1525#issuecomment-1436740646) (reinstall your dependencies).
