### ISSUE TITLE
MSW not intercepting request, no warnings, no uncaught, everything linked according examples

### ISSUE THREAD

**Issue by rnnyrk** [kettanaito/msw#1561]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

v16.14.2

### Reproduction repository

https://github.com/rnnyrk/workshop-testing

### Reproduction steps

- `git clone https://github.com/rnnyrk/workshop-testing`
- `npm install`
- `npm run test`

### Current behavior

MSW doesn't seem to work. In the `public` folder the `mockServiceWorker.js` is present. The `server` / `handlers` are setup according all examples I could find online.  Also commenting out the `handlers` do not present the "uncaught" API endpoint warning. 

In `src/__tests__/` folder the `jest.setup.js` contains:
```
import { server } from './mocks/server';

beforeAll(() => {
  server.listen();
});
afterEach(() => {
  server.resetHandlers();
});
afterAll(() => {
  server.close();
});
```

This `jest.setup.js` is linked in `jest.config.js` with `setupFilesAfterEnv: ['<rootDir>/src/__tests__/jest.setup.js'],`. 

No errors, no warnings, just nothing happens.

### Expected behavior

The API route /api/team is intercepted and returns the mocked response from `src/__tests__/mocks/data/team.json`.

**Comment by kettanaito** [comment]
Hi, @rnnyrk. Let me walk you through what happens in your test suite. 

I started by adding a bunch of logs to everything—the testing setup, the handlers, the `fetchTeam` function. Everything seems to be called, so Jest reaches that code during tests. However, notice the output of the query result during the test run:

```
// test starts...
// fetch happens...
{ data: undefined, isLoading: true, employees: undefined }

// fetch ends.
{ data: undefined, isLoading: false, employees: undefined }

// test ends.
```

Notice the second log output: no data but also no loading anymore. That likely means the third possible data state—error. Now, what happens if we also log `error` from the query:

```diff
export const Employees = () => {
-const { isLoading, data } = useGetTeam();
+const { isLoading, data, error } = useGetTeam();

-console.log({ data, isLoading, employees });
+console.log({ data, isLoading, employees, error });
}
```

Running the test now provides us with a rather useful error:

```
npm test -- src/__tests__/pages/team.test.tsx

   {
      data: undefined,
      isLoading: false,
      employees: undefined,
      error: ReferenceError: fetch is not defined
          at fetchTeam (/workshop-testing/src/queries/team/index.ts:9:20)
          at Object.fetchTeam [as queryFn] (/workshop-testing/src/queries/team/index.ts:15:43)
          at Object.queryFn [as fn] (/workshop-testing/node_modules/@tanstack/query-core/src/query.ts:397:27)
          at fn (/workshop-testing/node_modules/@tanstack/query-core/src/retryer.ts:145:31)
          at Object.run [as createRetryer] (/workshop-testing/node_modules/@tanstack/query-core/src/retryer.ts:201:5)
          at Query.createRetryer [as fetch] (/workshop-testing/node_modules/@tanstack/query-core/src/query.ts:450:20)
          at QueryObserver.fetch [as executeFetch] (/workshop-testing/node_modules/@tanstack/query-core/src/queryObserver.ts:327:70)
          at QueryObserver.executeFetch [as onSubscribe] (/workshop-testing/node_modules/@tanstack/query-core/src/queryObserver.ts:107:14)
          at QueryObserver.onSubscribe (/workshop-testing/node_modules/@tanstack/query-core/src/subscribable.ts:14:10)
          at subscribe (/workshop-testing/node_modules/@tanstack/react-query/src/useBaseQuery.ts:82:22)
          at subscribeToStore (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:16958:10)
          at commitHookEffectListMount (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:23150:26)
          at commitPassiveMountOnFiber (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:24931:11)
          at commitPassiveMountEffects_complete (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:24891:9)
          at commitPassiveMountEffects_begin (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:24878:7)
          at commitPassiveMountEffects (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:24866:3)
          at flushPassiveEffectsImpl (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:27039:3)
          at flushPassiveEffects (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:26984:14)
          at performSyncWorkOnRoot (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:26076:3)
          at flushSyncCallbacks (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:12042:22)
          at commitRootImpl (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:26959:3)
          at commitRoot (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:26682:5)
          at finishConcurrentRender (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:25981:9)
          at performConcurrentWorkOnRoot (/workshop-testing/node_modules/react-dom/cjs/react-dom.development.js:25809:7)
          at flushActQueue (/workshop-testing/node_modules/react/cjs/react.development.js:2667:24)
          at act (/workshop-testing/node_modules/react/cjs/react.development.js:2582:11)
          at /workshop-testing/node_modules/@testing-library/react/dist/act-compat.js:46:25
          at renderRoot (/workshop-testing/node_modules/@testing-library/react/dist/pure.js:161:26)
          at render (/workshop-testing/node_modules/@testing-library/react/dist/pure.js:247:10)
          at customRender (/workshop-testing/src/__tests__/test-utils.tsx:39:41)
          at Object.<anonymous> (/workshop-testing/src/__tests__/pages/team.test.tsx:21:68)
          at Promise.then.completed (/workshop-testing/node_modules/jest-circus/build/utils.js:293:28)
          at new Promise (<anonymous>)
          at callAsyncCircusFn (/workshop-testing/node_modules/jest-circus/build/utils.js:226:10)
          at _callCircusTest (/workshop-testing/node_modules/jest-circus/build/run.js:248:40)
          at processTicksAndRejections (node:internal/process/task_queues:95:5)
          at _runTest (/workshop-testing/node_modules/jest-circus/build/run.js:184:3)
          at _runTestsForDescribeBlock (/workshop-testing/node_modules/jest-circus/build/run.js:86:9)
          at _runTestsForDescribeBlock (/workshop-testing/node_modules/jest-circus/build/run.js:81:9)
          at run (/workshop-testing/node_modules/jest-circus/build/run.js:26:3)
          at runAndTransformResultsToJestFormat (/workshop-testing/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapterInit.js:120:21)
          at jestAdapter (/workshop-testing/node_modules/jest-circus/build/legacy-code-todo-rewrite/jestAdapter.js:79:19)
          at runTestInternal (/workshop-testing/node_modules/jest-runner/build/runTest.js:367:16)
          at runTest (/workshop-testing/node_modules/jest-runner/build/runTest.js:444:34)
          at Object.worker (/workshop-testing/node_modules/jest-runner/build/testWorker.js:106:12)
    }
```

The test is failing because you don't have `fetch` defined in your tests. Your `fetchTeams` uses `fetch` but that doesn't exist in Node prior to version 18. 

## How to solve this

1. Update to Node 18+. It ships `fetch` globally so the error will be gone. Note that although this option is a valid one to take, Jest is notoriously bad about meddling with Node.js globals so you may not get a proper standard Node API with Jest. 
2. Provide a fetch polyfill. You can use `whatwg-fetch`, and here's an [example of how to do that](https://github.com/mswjs/examples/blob/71a76d223296162f3af9bbb9d281a32421d00fc7/examples/with-jest/jest.setup.js#L1-L2).

I've tried the polyfill approach and your query does receive the mocked data now in the test. Your test is still failing but I assume you have to adjust your assertions to suit the data you're mocking.

**Comment by kettanaito** [comment]
If you like the project and would like for me to keep working on it and helping others debug issues like this, please consider [Sponsoring MSW](https://github.com/sponsors/mswjs). It helps a lot. Maybe one day it will be sustainable enough. Thank you.

**Comment by rnnyrk** [comment]
@kettanaito Thanks for your (quick) reply. Fixed the issue indeed! Might be good to add to a troubleshooting somewhere in the docs as well?

**Comment by kettanaito** [comment]
A good point. I have this added to the new docs I've been working on for quite some time. Would you like to open a PR to add the fetch polyfill to the FAQ page of our docs? https://github.com/mswjs/mswjs.io

**Comment by rnnyrk** [comment]
@kettanaito I'm for sure willing to do this, although i think the repository is private? At least i get an 404.

**Comment by kettanaito** [comment]
@rnnyrk, my bad, wrong repo name. Fixed it.
