### ISSUE TITLE
Can't pass `FormData` as body in jest test

### ISSUE THREAD

**Issue by danny-does-stuff** [kettanaito/msw#1577]
First off thanks for maintaining this awesome library, I know it's a lot of work, and it is a stellar library!

_______________________

When intercepting requests using MSW during jest tests (node environment), when I pass a `FormData` object as the body I get this `could not read FormData body as Blob` error

```
Error: could not read FormData body as blob
        at Request.Body.blob (/Users/dannyharding/infinid/src/simulation-creator/node_modules/whatwg-fetch/dist/fetch.umd.js:281:17)
        at Request.Body.arrayBuffer (/Users/dannyharding/infinid/src/simulation-creator/node_modules/whatwg-fetch/dist/fetch.umd.js:305:23)
        at FetchInterceptor.<anonymous> (/Users/dannyharding/infinid/src/simulation-creator/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:49:42)
        at step (/Users/dannyharding/infinid/src/simulation-creator/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:59:23)
        at Object.next (/Users/dannyharding/infinid/src/simulation-creator/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:40:53)
        at /Users/dannyharding/infinid/src/simulation-creator/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:34:71
        at new Promise (<anonymous>)
        at Object.<anonymous>.__awaiter (/Users/dannyharding/infinid/src/simulation-creator/node_modules/@mswjs/interceptors/lib/interceptors/fetch/index.js:30:12)
        at fetch (/Users/dannyharding/infinid/src/simulation-creator/node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:41:42)
        at uploadMissionGuides (/Users/dannyharding/infinid/src/simulation-creator/src/features/automatedSimulations/MissionGuide.js:150:23)
        at status (/Users/dannyharding/infinid/src/simulation-creator/src/features/automatedSimulations/MissionGuide.js:99:8)
        at generateAndUploadMissionGuides.next (<anonymous>)
        at uploadMissionGuides (/Users/dannyharding/infinid/src/simulation-creator/src/features/automatedSimulations/AutomatedSimulation.js:450:20)
        at async Promise.all (index 1)
        at Object.onClick (/Users/dannyharding/infinid/src/simulation-creator/src/features/automatedSimulations/AutomatedSimulation.js:402:9)
```

I would love to be able to use a FormData body in msw to test uploading files! 

## Research
I looked through code in msw, @msw/intercepters, and whatwg-fetch polyfill to try to figure out why this was happening and see if I could make it work in here in user land. I believe this is [the offending line in the msw fetch intercepter](https://github.com/mswjs/interceptors/blob/0c2f79db35b13a2db2dd9c5614a23b808d623220/src/interceptors/fetch/index.ts#L48), where the interceptor calls `.arrayBuffer` on the request (in this case a request with a `FormData` as the body), and that is simply not supported in the fetch polyfill, as you can see in [these lines in whatwg-fetch](https://github.com/github/fetch/blob/fb5b0cf42b470faf8c5448ab461d561f34380a30/fetch.js#L272-L273), where calling `.arrayBuffer` calls `.blob` which throws the error.

The good news is that this line in @msw/interceptors doesn't exist on newer versions! I'm not certain but I think that using a newer version of @msw/interceptors may fix this issue, but that may also make it necessary to drop support for node <18.

## The Request
I think there is a small chance I'm just wrong and there actually is a way to do this right now, and if that's the case please let me know! I would love to be able to test this functionality in my project. Otherwise, will you please let me know what the next steps might be or when this might be updated? Thanks again for this amazing library!

**Comment by kettanaito** [comment]
Hey, @danny-does-stuff. Thanks for reporting this and for the deep analyzis of the root cause!

I believe you are right about that `.arrayBuffer()` optimistic reading of request bodies. You have also rightfully pointed out that we don't do that in the newer versions of the Interceptors. 

I am unlikely to spend any time on this because this is already fixed in the Fetch API Beta release (#1436). It's still in beta and is a breaking change requiring a migration (luckily, I've written about it in #1464!) but you should give it a try today:

```sh
npm install msw@next
```

With that change, you can use `FormData` in Jest without issues (given you reset the global because Jest is special). This is also what I recommend to anybody encountering this: upgrade to `msw@next`.

**Comment by danny-does-stuff** [comment]
Oh yes I will definitely try this! What do you mean by resetting the global?

**Comment by kettanaito** [comment]
@danny-does-stuff, I mean that although you are on modern versions of Node, certain globals are purposefully stripped off in Jest. Such globals include `Request`, `Response`, `Headers`, etc. You can look up on the internet how to enable them back so Jest wouldn't complain about them. 

In the case of `FormData`, I believe it's also a Node.js global.

**Comment by christo8989** [comment]
I'm getting this issue with msw version 1.2.3 and node version 16.20.1

I tried running `npm install msw@next` but it's not working as described.

Is there any more information that I might be missing or is this issue worth reopening?

EDIT:

I also tried with node version 18 and 20.

**Comment by christo8989** [comment]
This is related. https://github.com/JakeChampion/fetch/issues/460

**Comment by kettanaito** [comment]
@christo8989, 

> I tried running npm install msw@next but it's not working as described.

Can you please elaborate on what behavior you are getting? The `next` version is stable and it has full support for `FormData`. Please bear in mind you have to follow the migration guidelines because it's a breaking change. Simply installing `msw@next` won't automatically fix this issue, **you have to migrate your app** to adjust to the breaking changes. This process is described in great detail in the [Migration guide](https://github.com/mswjs/msw/blob/feat/standard-api/MIGRATING.md).

If you are still experiencing issues after following that guide, submit your feedback in #1464 where I can look at it and address it. Thanks! 

I won't reopen this issue because there is no way of introducing `FormData` support to MSW 1.x without a significant overhaul of the library that was _already done_ in `msw@next`. Whoever is reading this, please migrate to the next version and enjoy standard-compliant API mocking. 

I will also lock this issue to prevent any further questions and to let this response be the last in the thread for better discoverability. Thanks.
