### ISSUE TITLE
"setTimeout" is not exported by "__vite-browser-external"

### ISSUE THREAD

**Issue by snowdream** [kettanaito/msw#1728]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Browsers

Chromium (Chrome, Brave, etc.)

### Reproduction repository

https://github.com/snowdreamtech/vue-nuxt-element-template

### Reproduction steps

```
pnpm install
pnpm build
```

### Current behavior

```
$ pnpm build

> element-plus-nuxt-starter@0.1.0 build D:\workspace\go\src\snowdream.tech\vue-nuxt-element-template
> MODE=prod nuxi build

Nuxt 3.7.0 with Nitro 2.6.2                                                                                               12:05:03

 WARN  JS / TS extension format is an experimental feature                                                   @nuxtjs/i18n 12:05:15

ℹ Building client...                                                                                                     12:05:32
ℹ vite v4.4.9 building for production...                                                                                 12:05:33

[12:05:53]  WARN  [plugin:vite:resolve] Module "timers" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/msw@1.2.5_typescript@5.2.2/node_modules/msw/lib/node/index.mjs". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:01]  WARN  [plugin:vite:resolve] Module "http" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:01]  WARN  [plugin:vite:resolve] Module "https" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/index.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:31]  WARN  [plugin:vite:resolve] Module "http" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/NodeClientRequest.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details. 


[12:06:31]  WARN  [plugin:vite:resolve] Module "http" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/normalizeClientRequestArgs.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:31]  WARN  [plugin:vite:resolve] Module "https" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/normalizeClientRequestArgs.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:44]  WARN  [plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/getIncomingMessageBody.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:44]  WARN  [plugin:vite:resolve] Module "zlib" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/getIncomingMessageBody.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:44]  WARN  [plugin:vite:resolve] Module "http" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/cloneIncomingMessage.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more 
details.


[12:06:44]  WARN  [plugin:vite:resolve] Module "stream" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/utils/cloneIncomingMessage.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.


[12:06:44]  WARN  [plugin:vite:resolve] Module "http" has been externalized for browser compatibility, imported by "D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/@mswjs+interceptors@0.17.9/node_modules/@mswjs/interceptors/lib/utils/getUrlByRequestOptions.js". See http://vitejs.dev/guide/troubleshooting.html#module-externalized-for-browser-compatibility for more details.

ℹ ✓ 2166 modules transformed.                                                                                            12:06:54
ℹ ✓ built in 1m 21s                                                                                                      12:06:54

[12:06:54]  ERROR  "setTimeout" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/msw@1.2.5_typescript@5.2.2/node_modules/msw/lib/node/index.mjs".
file: D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/msw@1.2.5_typescript@5.2.2/node_modules/msw/lib/node/index.mjs:28:9
26: 
27: // config/polyfills-node.ts
28: import { setTimeout as nodeSetTimeout } from "timers";
             ^
29: var setTimeout = nodeSetTimeout;


[12:06:54]  ERROR  Nuxt Build Error: "setTimeout" is not exported by "__vite-browser-external", imported by "node_modules/.pnpm/msw@1.2.5_typescript@5.2.2/node_modules/msw/lib/node/index.mjs".

  at error (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
  at Module.error (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:13716:16)
  at Module.traceVariable (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:14146:29)
  at ModuleScope.findVariable (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:12589:39)
  at Identifier.bind (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:8309:40)
  at VariableDeclarator.bind (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:5892:23)
  at VariableDeclaration.bind (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
  at Program.bind (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:5888:28)
  at Module.bindReferences (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:13712:18)
  at Graph.sortModules (/D:/workspace/go/src/snowdream.tech/vue-nuxt-element-template/node_modules/.pnpm/rollup@3.28.1/node_modules/rollup/dist/es/shared/node-entry.js:25770:20)

 ELIFECYCLE  Command failed with exit code 1.
```

### Expected behavior

build without error.

msw can be used in the production.

**Comment by snowdream** [comment]
'setTimeout' is not exported by __vite-browser-external, imported by node_modules/msw/lib/node/index.mjs

https://github.com/mswjs/msw/discussions/1440

**Comment by snowdream** [comment]
My Solution:

1. install rollup-plugin-node-polyfills
```
pnpm install -D rollup-plugin-node-polyfills
```

2. Edit nuxt.config.ts
```
// https://v3.nuxtjs.org/docs/directory-structure/nuxt.config
export default defineNuxtConfig({
  vite: {
    ...
    resolve: {
      alias: {
        timers: 'rollup-plugin-node-polyfills/polyfills/timers',
        path: 'rollup-plugin-node-polyfills/polyfills/path',
      },
    }, 
  },
```
