### ISSUE TITLE
TypeError: The "eventTargets" argument must be an instance of EventEmitter or EventTarget

### ISSUE THREAD

**Issue by kettanaito** [kettanaito/msw#1785]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v18

### Reproduction repository

https://github.com/mswjs/examples/actions/runs/6612009094/job/17956995430?pr=92

### Reproduction steps

```
pnpm test
```

### Current behavior

```
 Cause:
    TypeError: The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
```

### Expected behavior

No errors are thrown.

**Comment by kettanaito** [comment]
The issue seems to be specific to Jest. Once we migrate to Vitest, the usage examples would be the only reliable way to reproduce it. I suppose that's the price I'm willing to pay.

**Comment by the-ult** [comment]
Getting the same error when using with Jest (and Angular + Nx)

```

 >  NX   Report complete - copy this into the issue template

   Node   : 18.18.0
   OS     : win32-x64
   npm    : 10.1.0

   nx                 : 17.0.1
   @nx/js             : 17.0.1
   @nx/jest           : 17.0.1
   @nx/linter         : 17.0.1
   @nx/eslint         : 17.0.1
   @nx/workspace      : 17.0.1
   @nx/angular        : 17.0.1
   @nx/cypress        : 17.0.1
   @nx/devkit         : 17.0.1
   @nx/eslint-plugin  : 17.0.1
   @nx/playwright     : 17.0.1
   @nrwl/tao          : 17.0.1
   @nx/web            : 17.0.1
   @nx/webpack        : 17.0.1
   typescript         : 5.1.6
   ---------------------------------------
   Community plugins:
   @testing-library/angular : 14.3.0
```   

```
TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Zone'
        |     property '_zoneDelegate' -> object with constructor '_ZoneDelegate'
        --- property 'zone' closes the circle
        at stringify (<anonymous>)

      at messageParent (../../../node_modules/jest-worker/build/workers/messageParent.js:29:19)
```

Setup in an Nx repo:
- using the `jest.polyfills.ts` from the example
- In `jest.preset.js`
  ```ts
  const nxPreset = require('@nx/jest/preset').default;

  module.exports = {
    ...nxPreset,
    /// Since Jest strips the strips the NodeJs globals and we need them for
    /// MSW we need to explicitly add them again
    /// https://mswjs.io/docs/migrations/1.x-to-2.x#remap-fetch-api-globals
    globals: {
      fetch,
      FormData,
      Headers,
      ReadableStream,
      Request,
      Response,
      TextEncoder,
    },
    // setupFiles: ['/jest.polyfills.ts'],
   };
   ```
- In `libs/my-project/jest.config.ts`
  ```ts
  setupFiles: ['../../../jest.polyfills.ts'],
  ```

### Full stacktrace
```
● Test suite failed to run

    TypeError: Converting circular structure to JSON
        --> starting at object with constructor 'Zone'
        |     property '_zoneDelegate' -> object with constructor '_ZoneDelegate'
        --- property 'zone' closes the circle
  console.error
    Error: Uncaught [Error: Uncaught (in promise): TypeError [ERR_INVALID_ARG_TYPE]: The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
    TypeError: The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
        at new NodeError (node:internal/errors:405:5)
        at EventEmitter.setMaxListeners (node:events:330:17)
        at SetupServerApi.<anonymous> (...\node_modules\msw\lib\node\index.js:83:50)
        at Generator.next (<anonymous>)
        at ...\node_modules\msw\lib\node\index.js:36:61
        at new ZoneAwarePromise (...\node_modules\zone.js\bundles\zone.umd.js:1339:25)
        at __async (...\node_modules\msw\lib\node\index.js:20:10)
        at _Emitter.<anonymous> (...\node_modules\msw\lib\node\index.js:80:44)
        at emitAsync (...\node_modules\@mswjs\interceptors\lib\node\chunk-5PTPJLB7.js:50:20)
        at ...\node_modules\@mswjs\interceptors\lib\node\chunk-JCWVLTP7.js:682:44
        at until (...\node_modules\@open-draft\until\src\until.ts:23:24)
        at XMLHttpRequestController.xhrRequestController.onRequest (...\node_modules\@mswjs\interceptors\lib\node\chunk-JCWVLTP7.js:677:51)
        at XMLHttpRequest.methodCall (...\node_modules\@mswjs\interceptors\lib\node\chunk-JCWVLTP7.js:318:85)
        at Proxy.<anonymous> (...\node_modules\@mswjs\interceptors\lib\node\chunk-JCWVLTP7.js:176:29)
        at Observable._subscribe (...\node_modules\@angular\common\fesm2022\http.mjs:2190:21)
        at Observable.Object.<anonymous>.Observable._trySubscribe (...\node_modules\rxjs\src\internal\Observable.ts:244:19)
        at ...\node_modules\rxjs\src\internal\Observable.ts:234:18
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at ...\node_modules\rxjs\src\internal\operators\switchMap.ts:109:49
        at OperatorSubscriber._this._next (...\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
        at OperatorSubscriber.Object.<anonymous>.Subscriber.next (...\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
        at Observable._subscribe (...\node_modules\rxjs\src\internal\observable\innerFrom.ts:78:18)
        at Observable.Object.<anonymous>.Observable._trySubscribe (...\node_modules\rxjs\src\internal\Observable.ts:244:19)
        at ...\node_modules\rxjs\src\internal\Observable.ts:234:18
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at ...\node_modules\rxjs\src\internal\operators\switchMap.ts:100:12
        at OperatorSubscriber.<anonymous> (...\node_modules\rxjs\src\internal\util\lift.ts:24:18)
        at ...\node_modules\rxjs\src\internal\Observable.ts:226:22
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at ...\node_modules\rxjs\src\internal\operators\finalize.ts:70:14
        at OperatorSubscriber.<anonymous> (...\node_modules\rxjs\src\internal\util\lift.ts:24:18)
        at ...\node_modules\rxjs\src\internal\Observable.ts:226:22
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at doInnerSub (...\node_modules\rxjs\src\internal\operators\mergeInternals.ts:71:40)
        at outerNext (...\node_modules\rxjs\src\internal\operators\mergeInternals.ts:53:58)
        at OperatorSubscriber._this._next (...\node_modules\rxjs\src\internal\operators\OperatorSubscriber.ts:70:13)
        at OperatorSubscriber.Object.<anonymous>.Subscriber.next (...\node_modules\rxjs\src\internal\Subscriber.ts:75:12)
        at Observable._subscribe (...\node_modules\rxjs\src\internal\observable\innerFrom.ts:78:18)
        at Observable.Object.<anonymous>.Observable._trySubscribe (...\node_modules\rxjs\src\internal\Observable.ts:244:19)
        at ...\node_modules\rxjs\src\internal\Observable.ts:234:18
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at Object.mergeInternals (...\node_modules\rxjs\src\internal\operators\mergeInternals.ts:136:10)
        at ...\node_modules\rxjs\src\internal\operators\mergeMap.ts:95:42
        at OperatorSubscriber.<anonymous> (...\node_modules\rxjs\src\internal\util\lift.ts:24:18)
        at ...\node_modules\rxjs\src\internal\Observable.ts:226:22
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at ...\node_modules\rxjs\src\internal\operators\filter.ts:68:12
        at OperatorSubscriber.<anonymous> (...\node_modules\rxjs\src\internal\util\lift.ts:24:18)
        at ...\node_modules\rxjs\src\internal\Observable.ts:226:22
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at ...\node_modules\rxjs\src\internal\operators\map.ts:54:12
        at OperatorSubscriber.<anonymous> (...\node_modules\rxjs\src\internal\util\lift.ts:24:18)
        at ...\node_modules\rxjs\src\internal\Observable.ts:226:22
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at ...\node_modules\rxjs\src\internal\operators\map.ts:54:12
        at SafeSubscriber.<anonymous> (...\node_modules\rxjs\src\internal\util\lift.ts:24:18)
        at ...\node_modules\rxjs\src\internal\Observable.ts:226:22
        at Object.errorContext (...\node_modules\rxjs\src\internal\util\errorContext.ts:29:5)
        at Observable.Object.<anonymous>.Observable.subscribe (...\node_modules\rxjs\src\internal\Observable.ts:220:5)
        at _classThis.getZaakByCjibNummer (...\data-access\src\lib\vonnis.facade.ts:32:58)
        at _classThis.getData (...\feature-raadplegen\src\lib\feature-raadplegen.component.ts:21:24)
        at FeatureRaadplegenComponent_Template_button_click_2_listener (ng:///FeatureRaadplegenComponent.js:62:22)
        at executeListenerWithErrorHandling (...\node_modules\@angular\core\fesm2022\core.mjs:16773:16)
        at wrapListenerIn_markDirtyAndPreventDefault (...\node_modules\@angular\core\fesm2022\core.mjs:16806:22)
        at HTMLButtonElement.<anonymous> (...\node_modules\@angular\platform-browser\fesm2022\platform-browser.mjs:665:17)
        at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (...\node_modules\zone.js\bundles\zone.umd.js:445:35)
        at ProxyZoneSpec.Object.<anonymous>.ProxyZoneSpec.onInvokeTask (...\node_modules\zone.js\bundles\zone-testing.umd.js:331:43)
        at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (...\node_modules\zone.js\bundles\zone.umd.js:444:64)
        at AsyncStackTaggingZoneSpec.onInvokeTask (...\node_modules\@angular\core\fesm2022\core.mjs:10738:28)
        at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (...\node_modules\zone.js\bundles\zone.umd.js:444:64)
        at Object.onInvokeTask (...\node_modules\zone.js\bundles\zone.umd.js:323:104)
        at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (...\node_modules\zone.js\bundles\zone.umd.js:444:64)
        at Object.onInvokeTask (...\node_modules\@angular\core\fesm2022\core.mjs:11048:33)
        at _ZoneDelegate.Object.<anonymous>._ZoneDelegate.invokeTask (...\node_modules\zone.js\bundles\zone.umd.js:444:64)
        at Zone.Object.<anonymous>.Zone.runTask (...\node_modules\zone.js\bundles\zone.umd.js:210:51)
        at ZoneTask.Object.<anonymous>.ZoneTask.invokeTask [as invoke] (...\node_modules\zone.js\bundles\zone.umd.js:527:38)
        at invokeTask (...\node_modules\zone.js\bundles\zone.umd.js:1705:22)
        at globalCallback (...\node_modules\zone.js\bundles\zone.umd.js:1736:31)
        at HTMLButtonElement.globalZoneAwareCallback (...\node_modules\zone.js\bundles\zone.umd.js:1772:20)
        at HTMLButtonElement.callTheUserObjectsOperation (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\generated\EventListener.js:26:30)
        at innerInvokeEventListeners (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:350:25)       
        at invokeEventListeners (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:286:3)
        at HTMLButtonElementImpl._dispatch (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:233:9)  
        at HTMLButtonElementImpl.dispatchEvent (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\events\EventTarget-impl.js:104:17)
        at HTMLButtonElement.dispatchEvent (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\generated\EventTarget.js:241:34)   
        at ...\node_modules\@testing-library\user-event\dist\cjs\event\dispatchEvent.js:47:43
        at Object.eventWrapper (...\node_modules\@testing-library\angular\fesm2022\testing-library-angular.mjs:39:28)
        at Object.wrapEvent (...\node_modules\@testing-library\user-event\dist\cjs\event\wrapEvent.js:29:24)
        at Object.dispatchEvent (...\node_modules\@testing-library\user-event\dist\cjs\event\dispatchEvent.js:47:22)
        at Object.dispatchUIEvent (...\node_modules\@testing-library\user-event\dist\cjs\event\dispatchEvent.js:24:26)
        at Mouse.up (...\node_modules\@testing-library\user-event\dist\cjs\system\pointer\mouse.js:104:30)
        at PointerHost.release (...\node_modules\@testing-library\user-event\dist\cjs\system\pointer\index.js:86:28)]
        at reportException (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\living\helpers\runtime-script-errors.js:66:24)
        at Timeout.task [as _onTimeout] (...\node_modules\jest-environment-jsdom\node_modules\jsdom\lib\jsdom\browser\Window.js:525:9)
        at listOnTimeout (node:internal/timers:569:17)
        at processTimers (node:internal/timers:512:7) {
      detail: Error: Uncaught (in promise): TypeError [ERR_INVALID_ARG_TYPE]: The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
```

**Comment by dlvhdr** [comment]
I'm also getting this error.
I'm using urql to do graphql requests and have installed `undici` for the fetch implementation.
```
error: CombinedError {
        name: 'CombinedError',
        message: '[Network] Failed to fetch',
        graphQLErrors: [],
        networkError: TypeError: Failed to fetch
            at createNetworkError (/Users/dlvhdr/code/komodor/mono/node_modules/@mswjs/interceptors/lib/node/interceptors/fetch/index.js:140:24)
            at globalThis.fetch (/Users/dlvhdr/code/komodor/mono/node_modules/@mswjs/interceptors/lib/node/interceptors/fetch/index.js:80:31)
            at processTicksAndRejections (node:internal/process/task_queues:95:5) {
          cause: [TypeError]
        },
        response: undefined
      },
      cause: TypeError: The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
          at new NodeError (node:internal/errors:405:5)
          at EventEmitter.setMaxListeners (node:events:330:17)
          at SetupServerApi.<anonymous> (/Users/dlvhdr/code/komodor/mono/node_modules/msw/lib/node/index.js:83:50)
          at Generator.next (<anonymous>)
          at /Users/dlvhdr/code/komodor/mono/node_modules/msw/lib/node/index.js:36:61
          at new Promise (<anonymous>)
          at __async (/Users/dlvhdr/code/komodor/mono/node_modules/msw/lib/node/index.js:20:10)
          at _Emitter.<anonymous> (/Users/dlvhdr/code/komodor/mono/node_modules/msw/lib/node/index.js:80:44)
          at emitAsync (/Users/dlvhdr/code/komodor/mono/node_modules/@mswjs/interceptors/lib/node/chunk-5PTPJLB7.js:50:20)
          at /Users/dlvhdr/code/komodor/mono/node_modules/@mswjs/interceptors/lib/node/interceptors/fetch/index.js:59:62 {
        code: 'ERR_INVALID_ARG_TYPE'
      }```

**Comment by pord911** [comment]
Got the same issue, and with a bit of troubleshooting found this.

The failure occurs [here](https://github.com/mswjs/msw/blob/88c45ea5295fa7a47a943311dff65c99ebb3111e/src/node/SetupServerApi.ts#L67C11-L67C24).

```ts
          setMaxListeners(
            Math.max(defaultMaxListeners, this.currentHandlers.length),
            request.signal,
          )
```
`request.signal` is an isntance of AbortSignal, not `EventTarget` or `EventEmitter` which  `setMaxListeners` expects, and the error message indicates it. I don't think it's related to jest, it's rather node environment and fetch API implementation for node. I'm using node 18.
Check [setMaxListeners](https://nodejs.org/api/events.html#eventssetmaxlistenersn-eventtargets) for reference, the second argument should be an instance of EventTarget or EventEmitter. And AbortSignal is not.

Seems that fetch API implementation for node is based on undici, see [here](https://nodejs.org/en/blog/announcements/v18-release-announce#new-globally-available-browser-compatible-apis) for reference. Probably the AbortSignal in the Request object is not created as a proper nodejs signal construct. So, a quick fix could be to repackage the AbortSignal, if possible, to be an instance of EventEmitter. I don't know exactly the background behind setMaxListenerts here, would be good to know the background so that we can see if there is a solution to this. Or, if this could be an issue on the nodejs side of fetch api.

Would be good to see an example of a nodejs environment where this passes, if there is one.

**Comment by Ladrillo** [comment]
Also getting the TypeError: The "eventTargets" etc with fetch and jest. Repro repo [HERE](https://github.com/bloominstituteoftechnology/fetch-problem-msw2).

**Comment by macku** [comment]
We had the same problem with Jest, and after debugging the jest runtime, we decided to use [`patch-package`](https://www.npmjs.com/package/patch-package) to remove the broken checking of the Error instance. 

The part that is broken in Jest is related to the `isNodeException` function: 
https://github.com/mswjs/msw/blob/88c45ea5295fa7a47a943311dff65c99ebb3111e/src/node/utils/isNodeException.ts#L9

Here is the patch file:

```patch
diff --git a/node_modules/msw/lib/node/index.js b/node_modules/msw/lib/node/index.js
index 8022a9f..45039fe 100644
--- a/node_modules/msw/lib/node/index.js
+++ b/node_modules/msw/lib/node/index.js
@@ -85,7 +85,10 @@ var SetupServerApi = class extends import_SetupApi.SetupApi {
             request.signal
           );
         } catch (error) {
-          if (!(isNodeException(error) && error.code === "ERR_INVALID_ARG_TYPE")) {
+          if (!(/*
+          FIXME https://github.com/mswjs/msw/issues/1785
+          isNodeException(error) &&
+           */ error.code === "ERR_INVALID_ARG_TYPE")) {
             throw error;
           }
         }
diff --git a/node_modules/msw/lib/node/index.mjs b/node_modules/msw/lib/node/index.mjs
index 2ce5ebf..5f391ab 100644
--- a/node_modules/msw/lib/node/index.mjs
+++ b/node_modules/msw/lib/node/index.mjs
@@ -62,7 +62,10 @@ var SetupServerApi = class extends SetupApi {
             request.signal
           );
         } catch (error) {
-          if (!(isNodeException(error) && error.code === "ERR_INVALID_ARG_TYPE")) {
+          if (!(/*
+          FIXME https://github.com/mswjs/msw/issues/1785
+          isNodeException(error) &&
+           */ error.code === "ERR_INVALID_ARG_TYPE")) {
             throw error;
           }
         }
```

**Comment by mattcosta7** [comment]
> We had the same problem with Jest, and after debugging the jest runtime, we decided to use [`patch-package`](https://www.npmjs.com/package/patch-package) to remove the broken checking of the Error instance.
> 
> The part that is broken in Jest is related to the `isNodeException` function:
> 
> [msw/src/node/utils/isNodeException.ts](https://github.com/mswjs/msw/blob/88c45ea5295fa7a47a943311dff65c99ebb3111e/src/node/utils/isNodeException.ts#L9)
> 
> Line 9 in [88c45ea](/mswjs/msw/commit/88c45ea5295fa7a47a943311dff65c99ebb3111e)
> 
>  return error instanceof Error && 'code' in error 
> Here is the patch file:
> 
> diff --git a/node_modules/msw/lib/node/index.js b/node_modules/msw/lib/node/index.js
> index 8022a9f..45039fe 100644
> --- a/node_modules/msw/lib/node/index.js
> +++ b/node_modules/msw/lib/node/index.js
> @@ -85,7 +85,10 @@ var SetupServerApi = class extends import_SetupApi.SetupApi {
>              request.signal
>            );
>          } catch (error) {
> -          if (!(isNodeException(error) && error.code === "ERR_INVALID_ARG_TYPE")) {
> +          if (!(/*
> +          FIXME https://github.com/mswjs/msw/issues/1785
> +          isNodeException(error) &&
> +           */ error.code === "ERR_INVALID_ARG_TYPE")) {
>              throw error;
>            }
>          }
> diff --git a/node_modules/msw/lib/node/index.mjs b/node_modules/msw/lib/node/index.mjs
> index 2ce5ebf..5f391ab 100644
> --- a/node_modules/msw/lib/node/index.mjs
> +++ b/node_modules/msw/lib/node/index.mjs
> @@ -62,7 +62,10 @@ var SetupServerApi = class extends SetupApi {
>              request.signal
>            );
>          } catch (error) {
> -          if (!(isNodeException(error) && error.code === "ERR_INVALID_ARG_TYPE")) {
> +          if (!(/*
> +          FIXME https://github.com/mswjs/msw/issues/1785
> +          isNodeException(error) &&
> +           */ error.code === "ERR_INVALID_ARG_TYPE")) {
>              throw error;
>            }
>          }

I don't have a good chance to debug this currrently, but my expectation here is that the `Error` object in `jest` is not an `instanceof Error`

since you have a repro at hand, if you replace that `isNodeException` call with `'code' in error` does that succeed for you as well? (if not can you log what the error is in that case

I've, in the past, seen cases where jest/jsdom will do some fun global patching that can lead to these cases where an instance fails an instanceof check on what we _think_ it should succeed on

**Comment by pord911** [comment]
FYI
I can roughly confirm the case made by @mattcosta7 .

See highlighted local variable value.

![image](https://github.com/mswjs/msw/assets/7921607/c4ed339f-02e5-4e1a-945c-e793ff152f5a)

Happens when the TypeError in question is thrown.

My environment:
jest 27
jsdom 16
node 18
msw 2.0.0

Found [this](https://github.com/jsdom/jsdom/blob/a39e0ec4ce9a8806692d986a7ed0cd565ec7498a/Changelog.md?plain=1#L137) on jsdom changelog, even though it is for version 18 of jsdom, but here (in my environemnt) it seems to be the case as well.

**Comment by pord911** [comment]
FYI
Found these issues in jsdom which point to TypeError prototype chain being messed up in jsdom. This should further prove the instanceof point made by @mattcosta7 .

https://github.com/jsdom/jsdom/issues/3082
https://github.com/jsdom/jsdom/issues/2727

**Comment by mattcosta7** [comment]
thanks @pord911 a bit more digging here:

```ts
 console.log({
            error,
            errorName: error.name,
            constructor: error.constructor,
            constructorIsTypeError: error.constructor === globalThis.TypeError,
            isTypeError: error instanceof globalThis.TypeError,
            isError: error instanceof globalThis.Error,
          })
          if (!(isNodeException(error) && error.code === "ERR_INVALID_ARG_TYPE")) {
            throw error;
          }
```

```js
{
        error: TypeError [ERR_INVALID_ARG_TYPE]: The "eventTargets" argument must be an instance of EventEmitter or EventTarget. Received an instance of AbortSignal
            at new NodeError (node:internal/errors:406:5)
            at EventEmitter.setMaxListeners (node:events:329:17)
            at SetupServerApi.<anonymous> (/workspaces/examples/node_modules/.pnpm/msw@2.0.1_typescript@5.0.4/node_modules/msw/lib/node/index.js:83:50)
      ... {
          code: 'ERR_INVALID_ARG_TYPE'
        },
        errorName: 'TypeError',
        constructor: [Function: TypeError],
        constructorIsTypeError: false,
        isTypeError: false,
        isError: false
      }
```


updating the `isNodeException` to 

```ts
function isNodeExceptionLike(error) {
  return !!error && typeof error === "object" &&  "code" in error;
}
```

is decently well scoped, avoids instanceof checks and seems to work on `mswjs/examples`

**Comment by kettanaito** [comment]
## Released: v2.0.2 🎉

This has been released in v2.0.2!

- 📄 [**Release notes**](https://github.com/mswjs/msw/releases/tag/v2.0.2)
- 📦 [npm package](https://www.npmjs.com/package/msw/v/2.0.2)

Make sure to always update to the latest version (`npm i msw@latest`) to get the newest features and bug fixes.

---

_Predictable release automation by [@ossjs/release](https://github.com/ossjs/release)_.

**Comment by RobinClowers** [comment]
Amazing work everyone, thanks for turning this around so quickly! I can confirm this solved the issue for me.

**Comment by kettanaito** [comment]
@mattcosta7 is truly a wizard we are honored to have on our side.
