### ISSUE TITLE
Remix Error: ENOENT: no such file or directory, open '.../node_modules/msw/lib/core/handlers/RequestHandler.mjs.map'

### ISSUE THREAD

**Issue by amanape** [kettanaito/msw#1946]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.10.0

### Reproduction repository

https://github.com/amanape/remix-msw-client

### Reproduction steps

1. Create Remix app via `bunx create-remix@latest`.
2. Follow MSW documentation for browser and node integration.
3. Run `bun dev`

Note: Setting up only the browser mock allows the app to work fine, although does not actually intercept the requests. Implementing node mock causes the errors.

### Current behavior

Error when starting the app.

### Expected behavior

No error when starting the app.

**Comment by amanape** [comment]
Note the version I pushed on GitHub is 2.0.4, I downgraded it from 2.0.11 to test if I still get the same behaviour and unfortunately I do.

**Comment by MuzafferDede** [comment]
I am having the same error. Is there compatibility issue? 

```shell
Error: ENOENT: no such file or directory, open '/Users/username/Desktop/Code/remix-mws/node_modules/msw/lib/core/handlers/RequestHandler.mjs.map'
    at Object.readFileSync (node:fs:453:20)
    at Array.retrieveSourceMap (/Users/username/Desktop/Code/remix-mws/node_modules/@remix-run/serve/dist/cli.js:50:37)
    at /Users/username/Desktop/Code/remix-mws/node_modules/source-map-support/source-map-support.js:85:24
    at mapSourcePosition (/Users/username/Desktop/Code/remix-mws/node_modules/source-map-support/source-map-support.js:216:21)
    at wrapCallSite (/Users/username/Desktop/Code/remix-mws/node_modules/source-map-support/source-map-support.js:397:20)
    at Function.prepareStackTrace (/Users/username/Desktop/Code/remix-mws/node_modules/source-map-support/source-map-support.js:446:39)
    at maybeOverridePrepareStackTrace (node:internal/errors:142:29)
    at prepareStackTrace (node:internal/errors:116:5)
    at process.emit (/Users/username/Desktop/Code/remix-mws/node_modules/source-map-support/source-map-support.js:508:52)
    at process._fatalException (node:internal/process/execution:178:25) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/username/Desktop/Code/remix-mws/node_modules/msw/lib/core/handlers/RequestHandler.mjs.map'
}
```

**Comment by Shehab7assan** [comment]
I'm facing another related issue, should we use specific node version?

`node:internal/fs/utils:351
    throw err;
    ^

Error: ENOENT: no such file or directory, open '/Users/shehababbas/remix/remix-client/node_modules/msw/lib/core/utils/internal/getCallFrame.mjs.map'
    at Object.openSync (node:fs:596:3)
    at Object.readFileSync (node:fs:464:35)
    at Array.retrieveSourceMap (/Users/shehababbas/remix/remix-client/node_modules/@remix-run/serve/dist/cli.js:50:37)
    at /Users/shehababbas/remix/remix-client/node_modules/source-map-support/source-map-support.js:85:24
    at mapSourcePosition (/Users/shehababbas/remix/remix-client/node_modules/source-map-support/source-map-support.js:216:21)
    at wrapCallSite (/Users/shehababbas/remix/remix-client/node_modules/source-map-support/source-map-support.js:397:20)
    at Function.prepareStackTrace (/Users/shehababbas/remix/remix-client/node_modules/source-map-support/source-map-support.js:446:39)
    at maybeOverridePrepareStackTrace (node:internal/errors:140:29)
    at prepareStackTrace (node:internal/errors:114:5)
    at process.emit (/Users/shehababbas/remix/remix-client/node_modules/source-map-support/source-map-support.js:508:52) {
  errno: -2,
  syscall: 'open',
  code: 'ENOENT',
  path: '/Users/shehababbas/remix/remix-client/node_modules/msw/lib/core/utils/internal/getCallFrame.mjs.map'
}

Node.js v18.19.0`

**Comment by kettanaito** [comment]
This was caused by Remix hard-depending on third-parties publishing their sourcemaps. Since MSW didn't do that, you got the error. 

The sourcemaps support has since been added (#1958). Update to the latest version of MSW and let me know if you still get this error.
