### ISSUE TITLE
HttpResponse.json() throwing TypeError: Right-hand side of 'instanceof' is not an object.

### ISSUE THREAD

**Issue by Grieze** [kettanaito/msw#2076]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Node.js version

v20.11.0

### Reproduction repository

https://github.com/Grieze/wholesale-emarketplace/tree/feat-scaffholding

### Reproduction steps

Pull the repo, set node version to be 20.11.0 then run `npm ci` to bootstrap the project, then run `npm test -- CategorySideBar.test.tsx` to get the error in question. 

### Current behavior

I have followed all of the guides and read through the issues for MSW. 
The mock server successfully intercepts the request and it hits the correct endpoint, every crashes when I return an HttpResponse.json() object. I'm following the documentation to the letter, and the projects package.json says that msw supports node 20, and I've polyfilled the missing fetch library using `undici`.
Makes no sense why I am getting this type error:
```
TypeError: Failed to fetch

      at createNetworkError (node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:206:24)
      at globalThis.fetch (node_modules/@mswjs/interceptors/src/interceptors/fetch/index.ts:116:31)

    Cause:
    TypeError: Right-hand side of 'instanceof' is not an object

      24 |         };
      25 |         
    > 26 |         return HttpResponse.json({ query: mockCategories }, { status: 200 });
         |                             ^
      27 |     })
      28 | ];
      29 |

```
My jest.config.js file looks like so:
```
// jest.config.js
/** @type {import('ts-jest').JestConfigWithTsJest} */
module.exports = {
  rootDir: __dirname,
  preset: 'ts-jest',
  globals: { fetch },
  setupFiles: ['<rootDir>/jest.polyfills.js', '<rootDir>/setupEnvVar.js'],
  setupFilesAfterEnv: ['<rootDir>/jest.setup.ts'],
  testEnvironment: 'jest-environment-jsdom',
  testEnvironmentOptions: {
    customExportConditions: [''],
  },
  moduleNameMapper: {
    '\\.(css|less)$': '<rootDir>/__mocks__/styleMock.js',
  },
  transformIgnorePatterns: ['/node_modules/']
};
```
My polyfill file looks like so: 
```
// jest.polyfills.js
/**
 * @note The block below contains polyfills for Node.js globals
 * required for Jest to function when running JSDOM tests.
 * These HAVE to be require's and HAVE to be in this exact
 * order, since "undici" depends on the "TextEncoder" global API.
 *
 * Consider migrating to a more modern test runner if
 * you don't want to deal with this.
 */

const { TextDecoder, TextEncoder, ReadableStream } = require("node:util")

Object.defineProperties(globalThis, {
  TextDecoder: { value: TextDecoder },
  TextEncoder: { value: TextEncoder },
  ReadableStream: { value: ReadableStream },
})

const { Blob, File } = require("node:buffer")
const { fetch, Headers, FormData, Request, Response } = require("undici")

Object.defineProperties(globalThis, {
  fetch: { value: fetch, writable: true },
  Blob: { value: Blob },
  File: { value: File },
  Headers: { value: Headers },
  FormData: { value: FormData },
  Request: { value: Request },
  Response: { value: Response },
})
```

### Expected behavior

I expect the mock to return the json object but no dice, instead it freaks out saying that the right hand side is not an object. What could the issue be? Unless you guys are currently not supporting node 20 and I should just downgrade to latest version of node 18 instead.

**Comment by Grieze** [comment]
All I fixed the issue. The issue was how I was importing `ReadableStream`. It doesn't exist in the `node:util` library, instead I imported it as `const { ReadableStream } = require("stream/web");` and that resolved the issue and got MSW to work. It was throwing instance not an object error because ReadableStream was undefined. Stupid silly mistake, but it happens to the best of us. 

Going forward I believe this should be put in the docs as a common debugging problem that falls in line with the TextDecoder and TextEncoder being undefined.
