### ISSUE TITLE
graphql parsing blocked by try import graphql after the Jest environment has been torn down.

### ISSUE THREAD

**Issue by Shawn2Tang** [kettanaito/msw#2372]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 18 or higher

### Reproduction repository

https://github.com/mswjs/msw/issues

### Reproduction steps

test environment:
msw: 2.6.2
jest: 29.7.0
jest-environment-jsdom: 29.7.0
jest-fixed-jsdom: 0.0.9
apollo/client: 3.8.3

migrate by guidance of https://mswjs.io/docs/migrations/1.x-to-2.x

when test, msw will raise error:

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.                                                                                                                                                                                
      at parseQuery (node_modules/msw/src/core/utils/internal/parseGraphQLRequest.ts:50:21)                                                                                
      at parseGraphQLRequest (node_modules/msw/src/core/utils/internal/parseGraphQLRequest.ts:192:30)                                                                      
      at GraphQLHandler.parseGraphQLRequestOrGetFromCache (node_modules/msw/src/core/handlers/GraphQLHandler.ts:157:9)                                                     
      at GraphQLHandler.parse (node_modules/msw/src/core/handlers/GraphQLHandler.ts:180:26)                                                                                
      at GraphQLHandler.run (node_modules/msw/src/core/handlers/RequestHandler.ts:257:26)
      at executeHandlers (node_modules/msw/src/core/utils/executeHandlers.ts:36:14)
      at until (node_modules/@open-draft/until/src/until.ts:23:18)
      at handleRequest (node_modules/msw/src/core/utils/handleRequest.ts:63:24)
      at _Emitter.<anonymous> (node_modules/msw/src/node/SetupServerCommonApi.ts:62:26)
      at emitAsync (node_modules/@mswjs/interceptors/src/utils/emitAsync.ts:23:5)

Seems from:
async function parseQuery(query: string): Promise<ParsedGraphQLQuery | Error> {
  /**
   * @note Use `require` to get the "graphql" module here.
   * It has to be scoped to this function because this module leaks to the
   * root export. It has to be `require` because tools like Jest have trouble
   * handling dynamic imports. It gets replaced with a dynamic import on build time.
   */
  // eslint-disable-next-line @typescript-eslint/no-require-imports
  const { parse } = require('graphql')

  try {
    const ast = parse(query)
    return parseDocumentNode(ast)
  } catch (error) {
    return error as Error
  }
}

### Current behavior

ReferenceError: You are trying to `import` a file after the Jest environment has been torn down.     
                                                                                                                                                                           
      at parseQuery (node_modules/msw/src/core/utils/internal/parseGraphQLRequest.ts:50:21)                                                                                
      at parseGraphQLRequest (node_modules/msw/src/core/utils/internal/parseGraphQLRequest.ts:192:30)                                                                      
      at GraphQLHandler.parseGraphQLRequestOrGetFromCache (node_modules/msw/src/core/handlers/GraphQLHandler.ts:157:9)                                                     
      at GraphQLHandler.parse (node_modules/msw/src/core/handlers/GraphQLHandler.ts:180:26)                                                                                
      at GraphQLHandler.run (node_modules/msw/src/core/handlers/RequestHandler.ts:257:26)
      at executeHandlers (node_modules/msw/src/core/utils/executeHandlers.ts:36:14)
      at until (node_modules/@open-draft/until/src/until.ts:23:18)
      at handleRequest (node_modules/msw/src/core/utils/handleRequest.ts:63:24)
      at _Emitter.<anonymous> (node_modules/msw/src/node/SetupServerCommonApi.ts:62:26)
      at emitAsync (node_modules/@mswjs/interceptors/src/utils/emitAsync.ts:23:5)

### Expected behavior

Not raise error and correct parsing query.

**Comment by kettanaito** [comment]
Hi, @Shawn2Tang. It seems you haven't provided a reproduction repo. I'd have to close this issue as not reproducible. 

The error suggests that MSW still attempts to run when your tests are done. This often indicates that your tests aren't written correctly, e.g. they don't await asynchronous things. If you provide a minimal repo where I can reproduce this error, I can help you fix it. 

Please also read our document on the [Jest support](https://github.com/mswjs/msw/blob/main/decisions/jest-support.md). Thanks.
